version: '3.8'
services:
  web:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8100
    ports:
    - 8100:8100
    depends_on:
    - db
  db:
    image: postgres:13
    environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    ports:
    - 5432:5432

volumes:
  postgres-data: